name: CI

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            type: linux
            filename: pasta
          - os: macos-latest
            type: macos
            filename: pasta
          - os: windows-latest
            type: windows
            filename: pasta.exe
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: go build -v -o build/
      - name: Archive Binaries
        run: tar -cvf pasta-${{ matrix.type }}.tar build
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pasta-*.tar
